# Generated by Django 4.1 on 2022-09-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_diachi_user_sodienthoai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
