# Generated by Django 4.1 on 2022-09-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_ro',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
