# Generated by Django 4.1 on 2022-09-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_password_ro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.AddField(
            model_name='user',
            name='la_khachhang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='la_nhanvien',
            field=models.BooleanField(default=False),
        ),
    ]
