# Generated by Django 4.1 on 2022-09-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_is_customer_remove_user_is_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='madinhdanh',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='motanoidungyeucau',
            field=models.CharField(default='', max_length=100),
        ),
    ]
