# Generated by Django 4.1 on 2022-09-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_madinhdanh_user_motanoidungyeucau'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='socaukhaosat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='soluongkhaosat',
            field=models.IntegerField(default=0),
        ),
    ]
