# Generated by Django 4.1 on 2022-09-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_socaukhaosat_user_soluongkhaosat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='makhachhang',
            field=models.CharField(default='', max_length=100),
        ),
    ]
