# Generated by Django 4.1 on 2022-09-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_makhachhang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='makhachhang',
        ),
    ]
